# Generated by Django 5.2.6 on 2025-09-07 22:39

import apps.core.validators
import django.core.validators
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electrônicos'), ('FASHION', 'Moda'), ('HOME', 'Casa'), ('BEAUTY', 'Beleza'), ('SPORTS', 'Esportes'), ('TOYS', 'Brinquedos'), ('BOOKS', 'Livros'), ('MUSIC', 'Música'), ('GROCERY', 'Mercearia'), ('AUTOMOTIVE', 'Automotivo'), ('HEALTH', 'Saúde'), ('OFFICE', 'Escritório'), ('PETS', 'Animais de Estimação'), ('BABY', 'Bebê'), ('GARDEN', 'Jardim'), ('TOOLS', 'Ferramentas'), ('JEWELRY', 'Joias'), ('OTHER', 'Outros')], db_index=True, max_length=50, verbose_name='Departamento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço em BRL', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Estoque disponível', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque')),
                ('image', models.ImageField(blank=True, help_text='Tamanho máximo: 5MB. Formatos permitidos: JPG, JPEG, PNG.', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), apps.core.validators.FileSizeValidator(max_size=5242880)], verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created'],
            },
        ),
    ]
