# Generated by Django 5.2.6 on 2025-09-07 17:17

import apps.core.utils
import apps.core.validators
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('gender', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OTHER', 'Outro')], default='OTHER', max_length=10, verbose_name='Gênero')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Número de telefone')),
                ('cep', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_cep', message='CEP deve conter 8 dígitos.', regex='^\\d{8}$')], verbose_name='CEP')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('neighborhood', models.CharField(blank=True, max_length=50, verbose_name='Bairro')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('profile_picture', models.ImageField(blank=True, help_text='Tamanho máximo: 5MB. Formatos permitidos: JPG, JPEG, PNG.', upload_to=apps.core.utils.get_user_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), apps.core.validators.FileSizeValidator(max_size=5, unit='MB')], verbose_name='Foto de perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
